-- Tabela ARBITRO
DROP TABLE IF EXISTS ARBITRO CASCADE;
CREATE TABLE ARBITRO (
    ID BIGINT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    FEDERACAO VARCHAR(255),
    CATEGORIA VARCHAR(255),
    PARTIDAS_APITADAS INT DEFAULT 0
);

-- Tabela CAMPEONATO
DROP TABLE IF EXISTS CAMPEONATO CASCADE;
CREATE TABLE CAMPEONATO (
    ID BIGINT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    MATA_MATA BOOLEAN DEFAULT FALSE
);

-- Tabela ENUM_TIPO_ESPORTE (armazenar esportes do campeonato)
DROP TABLE IF EXISTS CAMPEONATO_ESPORTES CASCADE;
CREATE TABLE CAMPEONATO_ESPORTES (
    CAMPEONATO_ID BIGINT NOT NULL,
    ESPORTE VARCHAR(50),
    PRIMARY KEY (CAMPEONATO_ID, ESPORTE),
    FOREIGN KEY (CAMPEONATO_ID) REFERENCES CAMPEONATO(ID)
);

-- Tabela TEAMS (Times)
DROP TABLE IF EXISTS TEAMS CASCADE;
CREATE TABLE TEAMS (
    ID BIGINT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    ENUM_TIPO_ESPORTE VARCHAR(50)
);

-- Tabela PLAYERS (Jogadores)
DROP TABLE IF EXISTS PLAYERS CASCADE;
CREATE TABLE PLAYERS (
    ID BIGINT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    IDADE INT,
    EXPULSO BOOLEAN DEFAULT FALSE,
    NUM_CAMISA INT,
    POSICAO VARCHAR(100),
    CPF VARCHAR(20),
    TIPO_ESPORTE VARCHAR(50),
    GOLS INT DEFAULT 0,
    ASSISTENCIAS INT DEFAULT 0,
    CARTOES INT DEFAULT 0,
    PONTOS INT DEFAULT 0,
    CESTAS INT DEFAULT 0
);

-- Tabela CAMPEONATO_TIMES (Relacionamento muitos-para-muitos)
DROP TABLE IF EXISTS CAMPEONATO_TIMES CASCADE;
CREATE TABLE CAMPEONATO_TIMES (
    CAMPEONATO_ID BIGINT NOT NULL,
    TEAM_ID BIGINT NOT NULL,
    PRIMARY KEY (CAMPEONATO_ID, TEAM_ID),
    FOREIGN KEY (CAMPEONATO_ID) REFERENCES CAMPEONATO(ID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID)
);

-- Tabela TEAM_PLAYERS (Relacionamento muitos-para-muitos)
DROP TABLE IF EXISTS TEAM_PLAYERS CASCADE;
CREATE TABLE TEAM_PLAYERS (
    TEAM_ID BIGINT NOT NULL,
    PLAYER_ID BIGINT NOT NULL,
    PRIMARY KEY (TEAM_ID, PLAYER_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYERS(ID)
);

-- Tabela TABELA
DROP TABLE IF EXISTS TABELA CASCADE;
CREATE TABLE TABELA (
    ID BIGINT PRIMARY KEY,
    ID_CAMPEONATO BIGINT,
    FOREIGN KEY (ID_CAMPEONATO) REFERENCES CAMPEONATO(ID)
);

-- Tabela SUMULA
DROP TABLE IF EXISTS SUMULA CASCADE;
CREATE TABLE SUMULA (
    ID BIGINT PRIMARY KEY,
    ARBITRO_ID BIGINT,
    GOLS_MANDANTE INT DEFAULT 0,
    GOLS_VISITANTE INT DEFAULT 0,
    OBSERVACOES_RELATAS TEXT,
    DATA_FECHAMENTO TIMESTAMP,
    ASSINADA BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ARBITRO_ID) REFERENCES ARBITRO(ID)
);

-- Tabela SUMULA_OCORRENCIAS (Armazenar eventos da súmula)
DROP TABLE IF EXISTS SUMULA_OCORRENCIAS CASCADE;
CREATE TABLE SUMULA_OCORRENCIAS (
    SUMULA_ID BIGINT NOT NULL,
    OCORRENCIA VARCHAR(1000),
    PRIMARY KEY (SUMULA_ID, OCORRENCIA),
    FOREIGN KEY (SUMULA_ID) REFERENCES SUMULA(ID)
);

-- Tabela PARTIDA
DROP TABLE IF EXISTS PARTIDA CASCADE;
CREATE TABLE PARTIDA (
    ID BIGINT PRIMARY KEY,
    ID_TIME_MANDANTE BIGINT,
    ID_TIME_VISITANTE BIGINT,
    ID_CAMPEONATO BIGINT,
    ID_TABELA BIGINT,
    ID_VENCEDOR BIGINT,
    RESULTADO_VISITANTE INT DEFAULT 0,
    RESULTADO_MANDANTE INT DEFAULT 0,
    REALIZADA BOOLEAN DEFAULT FALSE,
    ENUM_FASE_PARTIDA VARCHAR(100),
    ARBITRO_ID BIGINT,
    SUMULA_ID BIGINT,
    FOREIGN KEY (ID_TIME_MANDANTE) REFERENCES TEAMS(ID),
    FOREIGN KEY (ID_TIME_VISITANTE) REFERENCES TEAMS(ID),
    FOREIGN KEY (ID_CAMPEONATO) REFERENCES CAMPEONATO(ID),
    FOREIGN KEY (ID_TABELA) REFERENCES TABELA(ID),
    FOREIGN KEY (ID_VENCEDOR) REFERENCES TEAMS(ID),
    FOREIGN KEY (ARBITRO_ID) REFERENCES ARBITRO(ID),
    FOREIGN KEY (SUMULA_ID) REFERENCES SUMULA(ID)
);
